mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url('', include('profile.urls')),
]

profile/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^sign_up$', views.sign_up, name='sign_up'),
    url(r'^log_out$', views.log_out, name='log_out'),
    url(r'^log_in$', views.log_in, name='log_in'),
    url(r'^edit$', views.edit_profile, name='edit_profile'),
    url(r'^profile$', views.profile, name='profile'),

]

profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=500, blank=True)
    last_name = models.CharField(max_length=500, blank=True)
    email = models.EmailField(max_length=500, blank=True)
    bio = models.TextField(max_length=500, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=Profile)
def model_post_save(sender, **kwargs):
    print("Object created/updated")


@receiver(post_delete, sender=Profile)
def model_post_delete(sender, **kwargs):
    print("Object deleted")

profile/forms.py
from django import forms
# from django.contrib.auth.forms import UserModel
from django.contrib.auth.forms import UserCreationForm
from profile.models import Profile
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2", ]


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'birth_date', 'bio', 'email', ]

profile/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate, logout
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import UserForm, UserProfileForm


def home(request):
    return render(request, 'profile/home.html', {})


def sign_up(request):
    if request.method == "POST":
        uform = UserForm(data=request.POST)
        pform = UserProfileForm(data=request.POST)
        if uform.is_valid() and pform.is_valid():
            user = User.objects.create_user(username=uform.cleaned_data["username"],
                                            password=uform.cleaned_data["password1"])
            profile = Profile.objects.create(user=user, **pform.cleaned_data)
            profile.save()
            return redirect('home')

    else:
        uform = UserForm()
        pform = UserProfileForm()
    return render(request, 'profile/sign_up.html', {'uform': uform,
                                                    'pform': pform})


def log_in(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            # Redirect to a success page.
            # profile = Profile.objects.filter(user=User.objects.filter(username=username))[0]
            profile = get_object_or_404(Profile, user=request.user)
            print(profile)
            return render(request, 'profile/profile.html', {'profile': profile})
    else:
        return render(request, 'profile/log_in.html', {})


def profile(request):
    profile = get_object_or_404(Profile, user=request.user)
    return render(request, 'profile/profile.html', {'profile': profile})


@login_required()
def edit_profile(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        pform = UserProfileForm(request.POST, instance=profile)
        if pform.is_valid():
            pform.save()
            return redirect('home')
    else:
        pform = UserProfileForm(instance=profile)
    return render(request, 'profile/edit.html', {'pform': pform, "object": request.user})


@login_required()
def log_out(request):
    logout(request)
    return redirect('home')

profile/templates/profile/base.html
{% load staticfiles %}

<html>
<head>
    <title>Profile</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">ProfileApp</a>
        </div>
        <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
            <li><a href="/profile">My Profile</a></li>
            <li><a href="/edit">Edit Profile</a></li>
            <li><a href="/log_out">Log Out</a></li>
            {% else %}
            <li><a href="/sign_up">Sign Up</a></li>
            <li><a href="/log_in">Log In</a></li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
            {% endblock %}
<!-- {{ SETTINGS.TEMPLATES }} -->
<script>
  $(function() {
    $( "#id_birth_date" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "1900:2012",
      // You can put more options here.

    });
  });

</script>
</body>
</html>

profile/templates/profile/edit.html
{% extends 'profile/base.html' %}
{% load temp_tag %}

{% block content %}
<h2>Edit Profile</h2>
<form method="post">
    {% csrf_token %}
    {{ pform.as_p }}
    <button type="submit">Confirm Changes</button>
</form>
{% block side_block %}
{% any_function  object %}
{% endblock %}
{% endblock %}

profile/templates/profile/home.html
{% extends 'profile/base.html' %}
{% block content %}
<h1>Welcome!</h1>
{% endblock content %}

profile/templates/profile/link.html
{% if object %}
    <a href="{% url 'admin:auth_user_change' object.id %}">Change User - {{object.username}}</a>
{% else %}
     <strong>No Object</strong>
{% endif %}

profile/templates/profile/log_in.html
{% extends 'profile/base.html' %}

{% block content %}
<h2>Log In</h2>
<form method="post">
    {% csrf_token %}
    Username:<br>
    <input type="text" name="username"><br>
    Password:<br>
    <input type="text" name="password"><br>
    <button type="submit">Log In</button>
</form>
{% endblock %}

profile/templates/profile/profile.html
{% extends 'profile/base.html' %}

{% block content %}
<h2>Profile</h2>
    {% csrf_token %}

<p> First Name {{ profile.first_name }}</p>
<p> Last Name {{ profile.last_name }}</p>
<p> Bio {{ profile.bio }}</p>
<p> Email {{ profile.email }}</p>
<p> Birth Date {{ profile.birth_date }}</p>
{% endblock %}

profile/templates/profile/sign_up.html
{% extends 'profile/base.html' %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {{ uform.as_p }}
    {{ pform.as_p }}
    <button type="submit">Sign up</button>
</form>
{% endblock %}